# Run build tasks, test tasks, and other generic tasks via the go-task tool:
# https://github.com/go-task/task
#
# The primary reason we're using this over something more standard like Make is
# that it provides a simple mechanism to skip tasks based on file checksums.
# This lets us more easily cache and skip steps in the CI and Docker
# development environment (since we only need to cache the build output and
# checksum files, rather than also needing to cache all the intermediate build
# files).
#
# A few general notes on the approach:
#
# - We mostly defer each task to a shell script to do the actual work.
# - For the build process, we use "stamp" files as outputs and also use those
#   within the dependency chain. We use these stamp files so that the
#   checksumming approach properly invalidates the entire chain of dependencies
#   when build files change (whereas just using "deps" in go-task doesn't fully
#   work for multiple levels of dependencies). So, for example, if the
#   libmaxminddb dependency changes, rebuilding it properly cascades and
#   triggers a rebuild of openresty (1st level dependency) and luarocks (2nd
#   level dependency).

version: "3"

output: interleaved

run: when_changed

tasks:
  deps:cue:
    cmds:
      - ./tasks/deps/cue
    sources:
      - ./tasks/deps/cue
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/deps/cue

  deps:envoy:
    deps:
      - build-deps:crane
    cmds:
      - ./tasks/deps/envoy
    sources:
      - ./build/work/stamp/build-deps/crane
      - ./tasks/deps/envoy
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/deps/envoy

  deps:envoy-control-plane:
    deps:
      - build-deps:crane
    cmds:
      - ./tasks/deps/envoy-control-plane
    sources:
      - ./build/work/stamp/build-deps/crane
      - ./tasks/deps/envoy-control-plane
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/deps/envoy-control-plane

  deps:fluent-bit:
    cmds:
      - ./tasks/deps/fluent-bit
    sources:
      - ./tasks/deps/fluent-bit
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/deps/fluent-bit

  deps:luarocks:
    deps:
      - deps:openresty
    cmds:
      - ./tasks/deps/luarocks
    sources:
      - ./build/work/stamp/deps/openresty
      - ./tasks/deps/luarocks
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/deps/luarocks

  deps:openresty:
    cmds:
      - ./tasks/deps/openresty
    sources:
      - ./tasks/deps/openresty
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/deps/openresty

  deps:perp:
    cmds:
      - ./tasks/deps/perp
    sources:
      - ./tasks/deps/perp
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/deps/perp

  deps:trafficserver:
    deps:
      - deps:openresty
    cmds:
      - ./tasks/deps/trafficserver
    sources:
      - ./build/work/stamp/deps/openresty
      - ./tasks/deps/trafficserver
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/deps/trafficserver

  deps:
    cmds:
      - task: deps:cue
      - task: deps:envoy
      - task: deps:envoy-control-plane
      - task: deps:fluent-bit
      - task: deps:luarocks
      - task: deps:openresty
      - task: deps:perp
      - task: deps:trafficserver

  build-deps:crane:
    cmds:
      - ./tasks/build-deps/crane
    sources:
      - ./tasks/build-deps/crane
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/build-deps/crane

  build-deps:hugo:
    cmds:
      - ./tasks/build-deps/hugo
    sources:
      - ./tasks/build-deps/hugo
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/build-deps/hugo

  build-deps:nodejs:
    cmds:
      - ./tasks/build-deps/nodejs
    sources:
      - ./tasks/build-deps/nodejs
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/build-deps/nodejs

  build-deps:pnpm:
    deps:
      - build-deps:nodejs
    cmds:
      - ./tasks/build-deps/pnpm
    sources:
      - ./build/work/stamp/build-deps/nodejs
      - ./tasks/build-deps/pnpm
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/build-deps/pnpm

  build-deps:
    cmds:
      - task: build-deps:crane
      - task: build-deps:hugo
      - task: build-deps:pnpm

  app-deps:admin-ui:pnpm:
    deps:
      - build-deps:pnpm
    cmds:
      - ./tasks/app-deps/admin-ui/pnpm
    sources:
      - ./build/work/stamp/build-deps/pnpm
      - ./src/api-umbrella/admin-ui/package.json
      - ./src/api-umbrella/admin-ui/pnpm-lock.yaml
      - ./tasks/app-deps/admin-ui/pnpm
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/app-deps/admin-ui/pnpm

  app-deps:example-website:pnpm:
    deps:
      - build-deps:pnpm
    cmds:
      - ./tasks/app-deps/example-website/pnpm
    sources:
      - ./build/work/stamp/build-deps/pnpm
      - ./src/api-umbrella/example-website/package.json
      - ./src/api-umbrella/example-website/pnpm-lock.yaml
      - ./tasks/app-deps/example-website/pnpm
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/app-deps/example-website/pnpm

  app-deps:luarocks:
    deps:
      - deps:luarocks
    cmds:
      - ./tasks/app-deps/luarocks
    sources:
      - ./build/work/stamp/deps/luarocks
      - ./src/api-umbrella-git-1.rockspec
      - ./src/luarocks.lock
      - ./tasks/app-deps/luarocks
      - ./tasks/helpers.sh
      - ./tasks/helpers/lua.sh
    generates:
      - ./build/work/stamp/app-deps/luarocks

  app-deps:web-app:pnpm:
    deps:
      - build-deps:pnpm
    cmds:
      - ./tasks/app-deps/web-app/pnpm
    sources:
      - ./build/work/stamp/build-deps/pnpm
      - ./src/api-umbrella/web-app/package.json
      - ./src/api-umbrella/web-app/pnpm-lock.yaml
      - ./tasks/app-deps/web-app/pnpm
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/app-deps/web-app/pnpm

  app-deps:
    cmds:
      - task: app-deps:admin-ui:pnpm
      - task: app-deps:example-website:pnpm
      - task: app-deps:luarocks
      - task: app-deps:web-app:pnpm

  app:admin-ui:build:
    deps:
      - app-deps:admin-ui:pnpm
    cmds:
      - ./tasks/app/admin-ui/build
    sources:
      - ./build/work/stamp/app-deps/admin-ui/pnpm
      - ./src/api-umbrella/admin-ui/app/**/*.hbs
      - ./src/api-umbrella/admin-ui/app/**/*.html
      - ./src/api-umbrella/admin-ui/app/**/*.js
      - ./src/api-umbrella/admin-ui/app/**/*.scss
      - ./src/api-umbrella/admin-ui/config/**/*.js
      - ./src/api-umbrella/admin-ui/ember-cli-build.js
      - ./src/api-umbrella/admin-ui/lib/**/*.js
      - ./tasks/app/admin-ui/build
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/app/admin-ui/build

  app:core:
    deps:
      - app:admin-ui:build
      - app:example-website:build
      - app:locale
      - app:web-app:precompile
    cmds:
      - ./tasks/app/core
    sources:
      - ./build/work/stamp/app/admin-ui/build
      - ./build/work/stamp/app/example-website/build
      - ./build/work/stamp/app/locale
      - ./build/work/stamp/app/web-app/precompile
      - ./tasks/app/core
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/app/core

  app:example-website:build:
    deps:
      - app-deps:example-website:pnpm
    cmds:
      - ./tasks/app/example-website/build
    sources:
      - ./build/work/stamp/app-deps/example-website/pnpm
      - ./src/api-umbrella/example-website/config.yaml
      - ./src/api-umbrella/example-website/assets/**/*
      - ./src/api-umbrella/example-website/content/**/*
      - ./src/api-umbrella/example-website/layouts/**/*
      - ./tasks/app/example-website/build
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/app/example-website/build

  app:locale:
    deps:
      - app-deps:admin-ui:pnpm
    cmds:
      - ./tasks/app/locale
    sources:
      - ./build/work/stamp/app-deps/admin-ui/pnpm
      - ./locale/*.po
      - ./tasks/app/locale
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/app/locale
    method: checksum

  app:web-app:precompile:
    deps:
      - app-deps:web-app:pnpm
    cmds:
      - ./tasks/app/web-app/precompile
    sources:
      - ./build/work/stamp/app-deps/web-app/pnpm
      - ./src/api-umbrella/web-app/assets/**/*.scss
      - ./src/api-umbrella/web-app/webpack.config.js
      - ./tasks/app/web-app/precompile
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/app/web-app/precompile

  app:
    cmds:
      - task: app:core

  all:
    cmds:
      - task: build-deps
      - task: deps
      - task: app-deps
      - task: app

  test-deps:bundle:
    cmds:
      - ./tasks/test-deps/bundle
    sources:
      - ./Gemfile
      - ./Gemfile.lock
      - ./tasks/test-deps/bundle
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/test-deps/bundle

  test-deps:glauth:
    cmds:
      - ./tasks/test-deps/glauth
    sources:
      - ./tasks/test-deps/glauth
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/test-deps/glauth

  test-deps:luarocks:
    deps:
      - deps:luarocks
    cmds:
      - ./tasks/test-deps/luarocks
    sources:
      - ./build/work/stamp/deps/luarocks
      - ./test/api-umbrella-git-1.rockspec
      - ./test/luarocks.lock
      - ./tasks/test-deps/luarocks
      - ./tasks/helpers.sh
      - ./tasks/helpers/lua.sh
    generates:
      - ./build/work/stamp/test-deps/luarocks

  test-deps:mailpit:
    cmds:
      - ./tasks/test-deps/mailpit
    sources:
      - ./tasks/test-deps/mailpit
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/test-deps/mailpit

  test-deps:shellcheck:
    cmds:
      - ./tasks/test-deps/shellcheck
    sources:
      - ./tasks/test-deps/shellcheck
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/test-deps/shellcheck

  test-deps:
    cmds:
      - task: test-deps:bundle
      - task: test-deps:glauth
      - task: test-deps:luarocks
      - task: test-deps:mailpit
      - task: test-deps:shellcheck

  lint:js:
    deps:
      - app-deps:admin-ui:pnpm
      - app-deps:example-website:pnpm
      - app-deps:web-app:pnpm
    cmds:
      - ./tasks/lint/js

  lint:lua:
    deps:
      - test-deps:luarocks
    cmds:
      - ./tasks/lint/lua

  lint:resty:
    deps:
      - test-deps:luarocks
    cmds:
      - ./tasks/lint/resty/run

  lint:ruby:
    deps:
      - test-deps:bundle
    cmds:
      - ./tasks/lint/ruby

  lint:shell:
    deps:
      - test-deps:shellcheck
    cmds:
      - ./tasks/lint/shell

  lint:
    cmds:
      - task: lint:js
      - task: lint:lua
      - task: lint:resty
      - task: lint:ruby
      - task: lint:shell

  update:luarocks:
    cmds:
      - ./tasks/update/luarocks

  update:packages:
    cmds:
      - ./tasks/helpers/test-bundle-exec thor outdated:update-packages

  update:test-deps:luarocks:
    cmds:
      - ./tasks/update/test-deps/luarocks

  outdated:
    cmds:
      - ./tasks/helpers/test-bundle-exec thor outdated:all

  outdated:packages:
    cmds:
      - ./tasks/helpers/test-bundle-exec thor outdated:packages

  test:
    cmds:
      - task: all
      - task: test-deps
      - ./tasks/helpers/test-bundle-exec thor test:test

  clean:dev:
    cmds:
      - ./tasks/clean/dev

  distclean:
    cmds:
      - ./tasks/distclean

  install:
    cmds:
      - ./tasks/install

  package:
    cmds:
      - ./tasks/package

  install-system-build-dependencies:
    cmds:
      - ./tasks/install-system-build-dependencies

  default:
    cmds:
      - task: all
