name: Renovate

on:
  push:
  schedule:
    - cron: "19 9 * * *"
  workflow_dispatch:
    inputs:
      override-repos:
        description: Override Repositories
      log-level:
        description: Log Level
        default: info
        type: choice
        options:
          - info
          - debug
      dry-run:
        description: Dry Run
        type: boolean

jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v42.0.4
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
          configurationFile: .github/renovate.json5
        env:
          LOG_LEVEL: ${{ inputs.log-level || 'debug' }}
          RENOVATE_DRY_RUN: full
          RENOVATE_BASE_BRANCHES: updates
          RENOVATE_USE_BASE_BRANCH_CONFIG: merge
